# Generated by Django 6.1 on 2026-08-31 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('membresias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoCuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_vencimiento', models.DateField()),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('membresia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuotas', to='membresias.membresia')),
                ('estado_cuota', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuotas', to='cuotas.estadocuota')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('membresia', 'periodo'), name='unique_cuota_membresia_periodo')],
            },
        ),
    ]
