# Generated by Django 6.1 on 2026-09-02 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuotas', '0003_estadocuota_descripcion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cuota',
            options={'ordering': ['-periodo'], 'verbose_name': 'Cuota', 'verbose_name_plural': 'Cuotas'},
        ),
        migrations.AlterModelOptions(
            name='estadocuota',
            options={'ordering': ['nombre'], 'verbose_name': 'Estado de cuota', 'verbose_name_plural': 'Estados de cuota'},
        ),
    ]
