# Generated by Django 6.1 on 2026-08-31 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoSocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Responsable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('dni', models.CharField(max_length=15, unique=True)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=100)),
                ('domicilio', models.CharField(blank=True, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('dni', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(blank=True, max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('domicilio', models.CharField(blank=True, max_length=150)),
                ('contacto_emergencia', models.CharField(blank=True, max_length=100)),
                ('apto_fisico', models.BooleanField(default=False)),
                ('fecha_ingreso', models.DateField()),
                ('estado_socio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='socios', to='socios.estadosocio')),
            ],
        ),
        migrations.CreateModel(
            name='SocioResponsable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parentesco', models.CharField(max_length=30)),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='socios', to='socios.responsable')),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsables', to='socios.socio')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('socio', 'responsable'), name='unique_socio_responsable')],
            },
        ),
    ]
