# Generated by Django 6.1 on 2026-08-31 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estadosocio',
            old_name='descripcion',
            new_name='nombre',
        ),
    ]
