# Generated by Django 6.1 on 2026-08-31 08:15

import django.core.validators
import apps.socios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0003_estadosocio_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='socio',
            name='estado_apto_fisico',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PRESENTADO', 'Presentado'), ('VENCIDO', 'Vencido')], default='PENDIENTE', max_length=20),
        ),
        migrations.AddField(
            model_name='socio',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='socio',
            name='fecha_presentacion_apto',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='socio',
            name='apto_fisico',
            field=models.FileField(blank=True, null=True, upload_to='aptos_fisicos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png']), apps.socios.models.validar_tamano_apto]),
        ),
    ]
