# Generated by Django 6.1 on 2026-09-03 22:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0004_socio_estado_apto_fisico_socio_fecha_nacimiento_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='socio',
            name='debe_cambiar_password',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='socio',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='socio', to=settings.AUTH_USER_MODEL),
        ),
    ]
