# Generated by Django 6.1 on 2026-09-03 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0005_socio_debe_cambiar_password_socio_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socio',
            name='debe_cambiar_password',
        ),
    ]
