# Generated by Django 6.1 on 2026-09-04 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0006_remove_socio_debe_cambiar_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socio',
            name='contacto_emergencia',
        ),
        migrations.AddField(
            model_name='socio',
            name='telefono_emergencia',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
