# Generated by Django 6.1 on 2026-09-04 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0007_remove_socio_contacto_emergencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='socio',
            name='nombre_contacto_emergencia',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='socio',
            name='relacion_contacto_emergencia',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
