# Generated by Django 6.1 on 2026-08-31 04:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('caja', '0001_initial'),
        ('cuotas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gastos_registrados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='caja',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='caja.caja'),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='cuota',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='cuotas.cuota'),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='gasto',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimiento', to='caja.gasto'),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='medio_pago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='caja.mediopago'),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='tipo_movimiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='caja.tipomovimiento'),
        ),
    ]
