# Generated by Django 6.1 on 2026-08-31 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estadocaja',
            old_name='descripcion',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='mediopago',
            old_name='descripcion',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='tipomovimiento',
            old_name='descripcion',
            new_name='nombre',
        ),
    ]
