# Generated by Django 6.1 on 2026-08-31 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0003_rename_descripcion_estadocaja_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadocaja',
            name='descripcion',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='mediopago',
            name='descripcion',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='tipomovimiento',
            name='descripcion',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
