# Generated by Django 6.1 on 2026-09-01 01:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0004_estadocaja_descripcion_mediopago_descripcion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConceptoMovimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='movimiento',
            name='detalle',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='concepto_movimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='caja.conceptomovimiento'),
        ),
    ]
