# Generated by Django 6.1 on 2026-09-02 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0005_conceptomovimiento_movimiento_detalle_and_more'),
        ('cuotas', '0004_alter_cuota_options_alter_estadocuota_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caja',
            options={'ordering': ['-fecha_apertura', '-hora_apertura'], 'verbose_name': 'Caja', 'verbose_name_plural': 'Cajas'},
        ),
        migrations.AlterModelOptions(
            name='categoriagasto',
            options={'ordering': ['nombre'], 'verbose_name': 'Categoría de gasto', 'verbose_name_plural': 'Categorías de gasto'},
        ),
        migrations.AlterModelOptions(
            name='conceptomovimiento',
            options={'ordering': ['nombre'], 'verbose_name': 'Concepto de movimiento', 'verbose_name_plural': 'Conceptos de movimiento'},
        ),
        migrations.AlterModelOptions(
            name='estadocaja',
            options={'ordering': ['nombre'], 'verbose_name': 'Estado de caja', 'verbose_name_plural': 'Estados de caja'},
        ),
        migrations.AlterModelOptions(
            name='gasto',
            options={'ordering': ['-fecha', '-hora'], 'verbose_name': 'Gasto', 'verbose_name_plural': 'Gastos'},
        ),
        migrations.AlterModelOptions(
            name='mediopago',
            options={'ordering': ['nombre'], 'verbose_name': 'Medio de pago', 'verbose_name_plural': 'Medios de pago'},
        ),
        migrations.AlterModelOptions(
            name='movimiento',
            options={'ordering': ['-fecha', '-hora'], 'verbose_name': 'Movimiento', 'verbose_name_plural': 'Movimientos'},
        ),
        migrations.AlterModelOptions(
            name='tipomovimiento',
            options={'ordering': ['nombre'], 'verbose_name': 'Tipo de movimiento', 'verbose_name_plural': 'Tipos de movimiento'},
        ),
        migrations.AddConstraint(
            model_name='movimiento',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('cuota__isnull', False), ('gasto__isnull', True)), models.Q(('cuota__isnull', True), ('gasto__isnull', False)), models.Q(('cuota__isnull', True), ('gasto__isnull', True)), _connector='OR'), name='movimiento_cuota_xor_gasto'),
        ),
    ]
