# Generated by Django 6.1 on 2026-08-31 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('socios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Canal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoNotificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoNotificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField()),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('canal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notificaciones', to='notificaciones.canal')),
                ('estado_notificacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notificaciones', to='notificaciones.estadonotificacion')),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='socios.socio')),
                ('tipo_notificacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notificaciones', to='notificaciones.tiponotificacion')),
            ],
        ),
    ]
