# Generated by Django 6.1 on 2026-08-31 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0002_rename_descripcion_canal_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='canal',
            name='descripcion',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='estadonotificacion',
            name='descripcion',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='tiponotificacion',
            name='descripcion',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
