# Generated by Django 6.1 on 2026-09-02 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0003_canal_descripcion_estadonotificacion_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='canal',
            options={'ordering': ['nombre'], 'verbose_name': 'Canal', 'verbose_name_plural': 'Canales'},
        ),
        migrations.AlterModelOptions(
            name='estadonotificacion',
            options={'ordering': ['nombre'], 'verbose_name': 'Estado de notificación', 'verbose_name_plural': 'Estados de notificación'},
        ),
        migrations.AlterModelOptions(
            name='notificacion',
            options={'ordering': ['-fecha_envio'], 'verbose_name': 'Notificación', 'verbose_name_plural': 'Notificaciones'},
        ),
        migrations.AlterModelOptions(
            name='tiponotificacion',
            options={'ordering': ['nombre'], 'verbose_name': 'Tipo de notificación', 'verbose_name_plural': 'Tipos de notificación'},
        ),
    ]
