# Generated by Django 6.1 on 2026-09-02 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_seed_configuracion_gimnasio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuraciongimnasio',
            options={'verbose_name': 'Configuración del gimnasio', 'verbose_name_plural': 'Configuración del gimnasio'},
        ),
    ]
