# Generated by Django 6.1 on 2026-08-31 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('socios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoMembresia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12)),
                ('vigencia_dias', models.PositiveIntegerField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planes', to='membresias.estadoplan')),
                ('tipo_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planes', to='membresias.tipoplan')),
            ],
        ),
        migrations.CreateModel(
            name='Membresia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('estado_membresia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='membresias', to='membresias.estadomembresia')),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='membresias', to='socios.socio')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='membresias', to='membresias.plan')),
            ],
        ),
    ]
