# Generated by Django 6.1 on 2026-08-31 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membresias', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estadomembresia',
            old_name='descripcion',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='estadoplan',
            old_name='descripcion',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='tipoplan',
            old_name='descripcion',
            new_name='nombre',
        ),
    ]
