# Generated by Django 6.1 on 2026-08-31 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membresias', '0002_rename_descripcion_estadomembresia_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadomembresia',
            name='descripcion',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='estadoplan',
            name='descripcion',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='tipoplan',
            name='descripcion',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
