# Generated by Django 6.1 on 2026-09-02 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membresias', '0003_estadomembresia_descripcion_estadoplan_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membresia',
            name='fecha_vencimiento',
            field=models.DateField(editable=False),
        ),
    ]
