# Generated by Django 6.1 on 2026-09-02 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membresias', '0004_alter_membresia_fecha_vencimiento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estadomembresia',
            options={'ordering': ['nombre'], 'verbose_name': 'Estado de membresía', 'verbose_name_plural': 'Estados de membresía'},
        ),
        migrations.AlterModelOptions(
            name='estadoplan',
            options={'ordering': ['nombre'], 'verbose_name': 'Estado de plan', 'verbose_name_plural': 'Estados de plan'},
        ),
        migrations.AlterModelOptions(
            name='membresia',
            options={'ordering': ['-fecha_inicio'], 'verbose_name': 'Membresía', 'verbose_name_plural': 'Membresías'},
        ),
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ['nombre'], 'verbose_name': 'Plan', 'verbose_name_plural': 'Planes'},
        ),
        migrations.AlterModelOptions(
            name='tipoplan',
            options={'ordering': ['nombre'], 'verbose_name': 'Tipo de plan', 'verbose_name_plural': 'Tipos de plan'},
        ),
    ]
