# Generated by Django 6.1 on 2026-08-31 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estadousuario',
            old_name='descripcion',
            new_name='nombre',
        ),
        migrations.AlterField(
            model_name='rol',
            name='descripcion',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
