# Generated by Django 6.1 on 2026-08-31 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_rename_descripcion_estadousuario_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadousuario',
            name='descripcion',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
