# Generated by Django 6.1 on 2026-09-02 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_estadousuario_descripcion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estadousuario',
            options={'ordering': ['nombre'], 'verbose_name': 'Estado de usuario', 'verbose_name_plural': 'Estados de usuario'},
        ),
        migrations.AlterModelOptions(
            name='rol',
            options={'ordering': ['nombre'], 'verbose_name': 'Rol', 'verbose_name_plural': 'Roles'},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
    ]
