# Generated by Django 6.1 on 2026-08-31 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('socios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoProfesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado_actividad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actividades', to='actividades.estadoactividad')),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(max_length=15)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('cupo', models.PositiveIntegerField()),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='horarios', to='actividades.actividad')),
            ],
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asistencias', to='socios.socio')),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asistencias', to='actividades.horario')),
            ],
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion', models.DateField(auto_now_add=True)),
                ('observacion', models.CharField(blank=True, max_length=200, null=True)),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='actividades.horario')),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='socios.socio')),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('dni', models.CharField(max_length=15, unique=True)),
                ('telefono', models.CharField(max_length=20)),
                ('telefono_2', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(max_length=100)),
                ('domicilio', models.CharField(blank=True, max_length=150)),
                ('estado_profesor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='profesores', to='actividades.estadoprofesor')),
            ],
        ),
    ]
