# Generated by Django 6.1 on 2026-08-31 04:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actividades', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profesor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='horario',
            name='profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='horarios', to='actividades.profesor'),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asistencias_registradas', to='actividades.profesor'),
        ),
        migrations.AddConstraint(
            model_name='inscripcion',
            constraint=models.UniqueConstraint(fields=('socio', 'horario'), name='unique_inscripcion_socio_horario'),
        ),
        migrations.AddConstraint(
            model_name='asistencia',
            constraint=models.UniqueConstraint(fields=('socio', 'horario', 'fecha'), name='unique_asistencia_socio_horario_fecha'),
        ),
    ]
