# Generated by Django 6.1 on 2026-08-31 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estadoactividad',
            old_name='descripcion',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='estadoprofesor',
            old_name='descripcion',
            new_name='nombre',
        ),
        migrations.AlterField(
            model_name='profesor',
            name='email',
            field=models.EmailField(blank=True, max_length=100),
        ),
    ]
