# Generated by Django 6.1 on 2026-09-07 00:28

import django.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0004_estadoactividad_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='fecha_ingreso',
            field=models.CharField(blank=True, verbose_name=django.db.models.fields.DateTimeField),
        ),
        migrations.AddField(
            model_name='profesor',
            name='fecha_nacimiento',
            field=models.CharField(blank=True, verbose_name=django.db.models.fields.DateField),
        ),
    ]
