# Generated by Django 6.1 on 2026-09-02 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0004_estadoactividad_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actividad',
            options={'ordering': ['nombre'], 'verbose_name': 'Actividad', 'verbose_name_plural': 'Actividades'},
        ),
        migrations.AlterModelOptions(
            name='asistencia',
            options={'ordering': ['-fecha', '-hora'], 'verbose_name': 'Asistencia', 'verbose_name_plural': 'Asistencias'},
        ),
        migrations.AlterModelOptions(
            name='estadoactividad',
            options={'ordering': ['nombre'], 'verbose_name': 'Estado de actividad', 'verbose_name_plural': 'Estados de actividad'},
        ),
        migrations.AlterModelOptions(
            name='estadoprofesor',
            options={'ordering': ['nombre'], 'verbose_name': 'Estado de profesor', 'verbose_name_plural': 'Estados de profesor'},
        ),
        migrations.AlterModelOptions(
            name='horario',
            options={'ordering': ['dia', 'hora_inicio'], 'verbose_name': 'Horario', 'verbose_name_plural': 'Horarios'},
        ),
        migrations.AlterModelOptions(
            name='inscripcion',
            options={'ordering': ['-fecha_inscripcion'], 'verbose_name': 'Inscripción', 'verbose_name_plural': 'Inscripciones'},
        ),
        migrations.AlterModelOptions(
            name='profesor',
            options={'ordering': ['apellido', 'nombre'], 'verbose_name': 'Profesor', 'verbose_name_plural': 'Profesores'},
        ),
    ]
