# Generated by Django 6.1 on 2026-09-04 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0005_alter_actividad_options_alter_asistencia_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='presente',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='horario',
            name='dia',
            field=models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miércoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sábado', 'Sábado'), ('Domingo', 'Domingo')], max_length=15),
        ),
    ]
