# Generated by Django 6.1 on 2026-09-07 00:49

import django.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0005_profesor_fecha_ingreso_profesor_fecha_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesor',
            name='fecha_ingreso',
            field=models.CharField(blank=True, verbose_name=django.db.models.fields.DateField),
        ),
    ]
