# Generated by Django 6.1 on 2026-09-07 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0006_alter_profesor_fecha_ingreso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesor',
            name='fecha_ingreso',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
