# Generated by Django 6.1 on 2026-09-12 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0007_alter_profesor_fecha_ingreso_and_more'),
        ('actividades', '0007_seed_estados_predefinidos'),
    ]

    operations = [
    ]
