# Generated by Django 6.1 on 2026-09-12 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0008_merge_20260912_2033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesor',
            name='fecha_ingreso',
        ),
        migrations.RemoveField(
            model_name='profesor',
            name='fecha_nacimiento',
        ),
    ]
